package hu.bme.iit.nfc.lockers.Domain;

public enum ProcessState {
    NONE,
    STARTINGRESERVE,
    CHALLENGERESERVE,
    RESERVING,
    DONE,
    STARTINGOPEN,
    CHALLENGEOPEN,
    CHALLENGEOPENSUCCESS,
    OPENING,
    SAVING,
    STARTINGCLOSE,
    CHALLENGECLOSE,
    CHALLENGECLOSESUCCESS,
    CLOSING,
    STARTINGRELEASE,
    CHALLENGERELEASE,
    CHALLENGERELEASESUCCESS,
    RELEASING,
}
