package com.tokenizer.p2p2;

public enum ProcessState {
    NONE,
    STARTINGRESERVE,
    RESERVING,
    SAVINGRESERVATION,
    DONE,
    STARTINGOPEN,
    OPENING,
    SAVINGOPENSTATE,
    STARTINGCLOSE,
    CLOSING,
    SAVINGCLOSEDSTATE,
    STARTINGRELEASE,

}
